language: node_js
node_js:
  - "5.2.0"
script: make ci
env:
services:
  - mysql
before_script:
  - mysql -e 'create database sqlmigrate_test;'
  - mysql -e "grant all privileges on sqlmigrate_test.* to travis@'%';"
notifications:
  email: false
